package inventorymanagementkadse242f035;

import database.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Dashboard extends javax.swing.JPanel {

    private JPanel container;

    public void setContainer(JPanel container) {
        this.container = container;
    }

    public Dashboard() {
        initComponents();
    }

    public void loadDashboard() {
        try {
            Connection con = DBConnection.DBHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rsCust = st.executeQuery("SELECT c.Cust_Name, SUM(o.Total_Price) AS Total " + "FROM orders o " + "JOIN customer c ON o.Cust_Id = c.Cust_Id " + "GROUP BY c.Cust_Name " + "ORDER BY Total DESC " + "LIMIT 1");

            if (rsCust.next()) {
                String bestCust = rsCust.getString("Cust_Name");
                lblBestCust.setText(bestCust);
            }

            ResultSet rsItem = st.executeQuery("SELECT i.Item_Name, SUM(oi.Qty) AS Total " + "FROM order_items oi " + "JOIN item i ON oi.Item_Id = i.Item_Id " + "GROUP BY i.Item_Name " + "ORDER BY Total DESC " + "LIMIT 1");
            if (rsItem.next()) {
                String bestItem = rsItem.getString("Item_Name");
                lblBestItem.setText(bestItem);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblBestItem = new javax.swing.JLabel();
        btnSeeReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBestCust = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel2.setText("Best Selling Item");

        lblBestItem.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        lblBestItem.setText("Item");

        btnSeeReport.setBackground(new java.awt.Color(4, 61, 142));
        btnSeeReport.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnSeeReport.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeReport.setText("See Report");
        btnSeeReport.setBorder(null);
        btnSeeReport.setPreferredSize(new java.awt.Dimension(89, 29));
        btnSeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblBestItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBestItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel3.setText("Best Customer");

        lblBestCust.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        lblBestCust.setText("Customer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblBestCust)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblBestCust)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Container.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeReportActionPerformed
        try {
            Connection con = DBConnection.DBHelper.getConnection();
            Statement st = con.createStatement();

            JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\wickr\\OneDrive\\Documents\\NetBeansProjects\\InventoryManagementKADSE242F035\\src\\reports\\BestItem.jrxml");

            String query = "SELECT i.Item_Name, SUM(oi.Qty) AS Total "
                    + "FROM order_items oi "
                    + "JOIN item i ON oi.Item_Id = i.Item_Id "
                    + "GROUP BY i.Item_Name "
                    + "ORDER BY Total DESC "
                    + "LIMIT 5";
            
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jDesign.setQuery(updateQuery);
            
            JasperReport jreport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null,con);
            
            JasperViewer.viewReport(jprint, false);

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (JRException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnSeeReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeeReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBestCust;
    private javax.swing.JLabel lblBestItem;
    // End of variables declaration//GEN-END:variables
}
