package inventorymanagementkadse242f035;

import database.DBConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class Order extends javax.swing.JPanel {

    private JPanel container;

    public void setContainer(JPanel container) {
        this.container = container;
    }

    public Order() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNewOrder = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(140, 148, 156));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel1.setText("Manage Order");

        btnNewOrder.setBackground(new java.awt.Color(4, 61, 142));
        btnNewOrder.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setText("New Order");
        btnNewOrder.setBorder(null);
        btnNewOrder.setPreferredSize(new java.awt.Dimension(89, 29));
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnCheckout.setBackground(new java.awt.Color(4, 61, 142));
        btnCheckout.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Checkout");
        btnCheckout.setBorder(null);
        btnCheckout.setPreferredSize(new java.awt.Dimension(89, 29));
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(4, 61, 142));
        btnDelete.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setPreferredSize(new java.awt.Dimension(89, 29));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_Id", "Customer_Id", "Date"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(900, 700));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(416, 416, 416)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        System.out.println("Loading New Order");
        NewOrder newOrderPanel = new NewOrder();
        newOrderPanel.setContainer(container);
        container.add(newOrderPanel, BorderLayout.CENTER);

        if (container == null) {
            JOptionPane.showMessageDialog(this, "Error: container panel not set!");
            return;
        }
        container.removeAll();
        // Load the customer panel

        container.setLayout(new BorderLayout());
        container.add(newOrderPanel, BorderLayout.CENTER);
        // Refresh the panel
        container.revalidate();
        container.repaint();
        newOrderPanel.loadCustomerData();
        newOrderPanel.loadItemData();
        newOrderPanel.loadForm();
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        /*String custName = txtCustName.getText();
        String custPhone = txtCustPhone.getText();
        String custEmail = txtCustEmail.getText();

        if (validateFields("new")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                Connection con = DBConnection.DBHelper.getConnection();
                PreparedStatement pstmt = con.prepareStatement("insert into customer (Cust_Name, Phone, Email ) VALUES (?, ?, ?)");
                pstmt.setString(1, custName);
                pstmt.setString(2, custPhone);
                pstmt.setString(3, custEmail);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Customer Registered Successfully");
                setVisible(true);
                loadCustomerData();
                clearForm();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }*/
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        /*String custName = txtCustName.getText();
        String custPhone = txtCustPhone.getText();
        String custEmail = txtCustEmail.getText();

        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "Select Item To Delete");
        } else {
            int conDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this customer?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (conDelete == 0) {
                try {
                    Connection con = DBConnection.DBHelper.getConnection();
                    PreparedStatement pstmt = con.prepareStatement("DELETE FROM `customer` WHERE `Cust_Id` = ? AND `Cust_Name` = ? AND `Phone` = ? AND `Email` = ?");
                    pstmt.setInt(1, custPk);
                    pstmt.setString(2, custName);
                    pstmt.setString(3, custPhone);
                    pstmt.setString(4, custEmail);
                    int rowsAffected = pstmt.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Customer Deleted Successfully");
                        setVisible(true);
                        loadCustomerData();
                        clearForm();
                    } else {
                        JOptionPane.showMessageDialog(null, "Customer Not Found");
                    }

                } catch (Exception e) {
                    JOptionPane.showInternalMessageDialog(null, e);

                }
            }
        }*/
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
