package inventorymanagementkadse242f035;

import database.DBConnection;
import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class User extends javax.swing.JPanel {

    private int userPk = 0;

    public User() {
        initComponents();
        btnUpdate.setEnabled(false);
        Helper.loadBranchesIntoComboBox(comBoxBranch);
        comBoxBranch.setEditable(true);
        AutoCompleteDecorator.decorate(comBoxBranch);
        comBoxRole.setEditable(true);
        AutoCompleteDecorator.decorate(comBoxRole);
        comBoxStatus.setEditable(true);
        AutoCompleteDecorator.decorate(comBoxStatus);
    }

//Method to Load Data from the DB
    public void loadUserData() {
        System.out.println("Loading user data");
        comBoxRole.setSelectedIndex(-1);
        comBoxBranch.setSelectedIndex(-1);
        comBoxStatus.setSelectedIndex(-1);
        DefaultTableModel model = (DefaultTableModel) tableUser.getModel();
        model.setRowCount(0); // Clear previous rows

        try {
            Connection con = DBConnection.DBHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM user");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("Name"),
                    rs.getString("Username"),
                    rs.getString("Role"),
                    rs.getString("Email"),
                    rs.getString("Phone_number"),
                    rs.getString("NIC"),
                    rs.getString("Status")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

//Clear the fields 
    public void clearForm() {
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtPassword.setEditable(true);
        txtPassword.setBackground(Color.WHITE);
        comBoxRole.setSelectedIndex(-1);
        txtEmail.setText("");
        txtPhone.setText("");
        txtNIC.setText("");
        comBoxBranch.setSelectedIndex(-1);
        comBoxStatus.setSelectedIndex(-1);

    }

    private boolean validateFields(String formType) {
        if (formType.equals("edit")
                && !txtName.getText().equals("")
                && !txtUsername.getText().equals("")
                && !txtEmail.getText().equals("")
                && !txtPhone.getText().equals("")
                //&& !txtBranch.getText().equals("")
                && !txtNIC.getText().equals("")) {
            return false;
        } else if (formType.equals("new")
                && !txtName.getText().equals("")
                && !txtUsername.getText().equals("")
                && !txtPassword.getText().equals("")
                && !txtEmail.getText().equals("")
                && !txtPhone.getText().equals("")
                //&& !txtBranch.getText().equals("")
                && !txtNIC.getText().equals("")) {
            return false;

        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        comBoxStatus = new javax.swing.JComboBox<>();
        comBoxRole = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        comBoxBranch = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Role", "Email", "Status", "Phone Number", "NIC", "Branch"
            }
        ));
        tableUser.setPreferredSize(new java.awt.Dimension(1000, 300));
        tableUser.setShowGrid(true);
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);

        jPanel1.setBackground(new java.awt.Color(140, 148, 156));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel1.setText("User Registration");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel5.setText("Role");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel8.setText("NIC");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel9.setText("Branch");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel10.setText("Status");

        txtName.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtName.setPreferredSize(new java.awt.Dimension(200, 28));

        txtUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtUsername.setPreferredSize(new java.awt.Dimension(200, 28));

        txtPassword.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(200, 28));

        txtEmail.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 28));

        txtPhone.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtPhone.setPreferredSize(new java.awt.Dimension(200, 28));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        txtNIC.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        txtNIC.setPreferredSize(new java.awt.Dimension(200, 28));

        comBoxStatus.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        comBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        comBoxStatus.setPreferredSize(new java.awt.Dimension(200, 28));
        comBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxStatusActionPerformed(evt);
            }
        });

        comBoxRole.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        comBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Other" }));

        btnUpdate.setBackground(new java.awt.Color(4, 61, 142));
        btnUpdate.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setPreferredSize(new java.awt.Dimension(89, 29));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(4, 61, 142));
        btnSave.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.setPreferredSize(new java.awt.Dimension(89, 29));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(4, 61, 142));
        btnDelete.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setPreferredSize(new java.awt.Dimension(89, 29));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(4, 61, 142));
        btnReset.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.setPreferredSize(new java.awt.Dimension(89, 29));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        comBoxBranch.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        comBoxBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comBoxBranch.setPreferredSize(new java.awt.Dimension(200, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comBoxRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(130, 130, 130)
                                            .addComponent(comBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(60, 60, 60)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(148, 148, 148))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(124, 124, 124)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void comBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxStatusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        setVisible(true);
        clearForm();
        loadUserData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        int index = tableUser.getSelectedRow();

        if (index >= 0) {
            TableModel model = tableUser.getModel();

            String id = model.getValueAt(index, 0).toString();
            userPk = Integer.parseInt(id);

            String name = model.getValueAt(index, 1).toString();
            txtName.setText(name);

            String username = model.getValueAt(index, 2).toString();
            txtUsername.setText(username);

            txtPassword.setEditable(false);
            txtPassword.setBackground(Color.GRAY);

            String role = model.getValueAt(index, 3).toString();
            comBoxRole.setSelectedItem(role);

            String email = model.getValueAt(index, 4).toString();
            txtEmail.setText(email);

            String phone = model.getValueAt(index, 5).toString();
            txtPhone.setText(phone);

            String nic = model.getValueAt(index, 6).toString();
            txtNIC.setText(nic);

            String branch = model.getValueAt(index, 7).toString();
            comBoxBranch.setSelectedItem(branch);

            String status = model.getValueAt(index, 8).toString();
            comBoxStatus.setSelectedItem(status);

            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        }

    }//GEN-LAST:event_tableUserMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        System.out.println("Updatign Data");//Testing the update button
        String name = txtName.getText();
        String user = txtUsername.getText();
        String role = (String) comBoxRole.getSelectedItem();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String nic = txtNIC.getText();
        String branch = (String) comBoxBranch.getSelectedItem();
        String status = (String) comBoxStatus.getSelectedItem();

        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                Connection con = DBConnection.DBHelper.getConnection();
                PreparedStatement pstmt = con.prepareStatement("update user set Name=?, Username=?, Role=?, Email=?, Phone_Number=?, NIC=?, Branch=?, Status=? where ID=?");
                //String selectedUserId = null;

                pstmt.setString(1, name);
                pstmt.setString(2, user);
                pstmt.setString(3, role);
                pstmt.setString(4, email);
                pstmt.setString(5, phone);
                pstmt.setString(6, nic);
                pstmt.setString(7, branch);
                pstmt.setString(8, status);
                pstmt.setInt(9, userPk);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "User Updated Successfully");
                setVisible(true);
                loadUserData();
                clearForm();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtName.getText();
        String user = txtUsername.getText();
        String pass = txtPassword.getText();
        String role = (String) comBoxRole.getSelectedItem();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String nic = txtNIC.getText();
        String branch = (String) comBoxBranch.getSelectedItem();
        String branchName[] = branch.split("-", 0);
        String status = (String) comBoxStatus.getSelectedItem();

        if (validateFields("new")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                Connection con = DBConnection.DBHelper.getConnection();
                PreparedStatement pstmt = con.prepareStatement("insert into user (Name, Username, Password, Role, Email, Phone_Number, NIC, Branch, Status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
                pstmt.setString(1, name);
                pstmt.setString(2, user);
                pstmt.setString(3, pass);
                pstmt.setString(4, role);
                pstmt.setString(5, email);
                pstmt.setString(6, phone);
                pstmt.setString(7, nic);
                pstmt.setString(8, branch);
                pstmt.setString(9, status);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "User Added Successfully");
                setVisible(true);
                loadUserData();
                clearForm();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String name = txtName.getText();
        String user = txtUsername.getText();
        String pass = txtPassword.getText();
        String role = (String) comBoxRole.getSelectedItem();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String nic = txtNIC.getText();
        String branch = (String) comBoxBranch.getSelectedItem();
        String status = (String) comBoxStatus.getSelectedItem();
        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "Select User To Delete");
        } else {
            int conDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (conDelete == 0) {
                try {
                    Connection con = DBConnection.DBHelper.getConnection();
                    PreparedStatement pstmt = con.prepareStatement("DELETE FROM `user` WHERE `Id` = ? AND `Name` = ? AND `Username` = ? AND `Role` = ? AND `Email` = ? AND `Phone_Number` = ? AND `NIC` = ? AND `Branch` = ? AND `Status` = ?");
                    pstmt.setInt(1, userPk);
                    pstmt.setString(2, name);
                    pstmt.setString(3, user);
                    pstmt.setString(4, role);
                    pstmt.setString(5, email);
                    pstmt.setString(6, phone);
                    pstmt.setString(7, nic);
                    pstmt.setString(8, branch);
                    pstmt.setString(9, status);
                    int rowsAffected = pstmt.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "User Deleted Successfully");
                        setVisible(true);
                        loadUserData();
                        clearForm();
                    } else {
                        JOptionPane.showMessageDialog(null, "User Not Found");
                    }

                } catch (Exception e) {
                    JOptionPane.showInternalMessageDialog(null, e);

                }
            }
        }


    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comBoxBranch;
    private javax.swing.JComboBox<String> comBoxRole;
    private javax.swing.JComboBox<String> comBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
